#!/usr/bin/env python

import sys, os
import rospy
from nav_msgs.msg import OccupancyGrid
from subprocess import check_output
from threading import Thread

class MapKeeper:
    def __init__(self, map_args):
        self.mapping = True
        self.map_args = map_args
        rospy.Subscriber('/map', OccupancyGrid, self.map_cb)
        self.map = OccupancyGrid()
        
    def map_cb(self, msg):
        if self.mapping:
            # compare maps
            if msg.data == self.map.data:
                self.mapping = False
                self.thread = Thread(target = self.save_map)
                self.thread.start()
            else:           
                self.map = msg
                print('Receiving map...')
                
    def save_map(self):
        print('Saving map...')
        out = check_output(('rosrun map_server map_saver ' + self.map_args).split())
        

if __name__ == "__main__":
    
    rospy.init_node('map_saver_memory')
    
    #map_args = sys.argv[1]
    map_args = '--occ 65 --free 2 -f /home/olivier/code/ros/src/ecn/mobro/maps/house'
    
    listener = MapKeeper(map_args)
    save_running = False
    
    while not rospy.is_shutdown():
        
        if not listener.mapping and not listener.thread.isAlive():
            print('Map saved')
            break
            
        rospy.sleep(1.)
    
